### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by dricholm** [westracer/fontify#1]
Hello @westracer,

Thanks for this package! So far it works great for me.

Currently I am using it as a dev dependency in a project, where I have the svg files in the assets folder and added the generated font and dart class to `.gitignore`. So it works in a similar way as build_runner generated files.
But to generate the desired output I always have to specify all the arguments and options in the command, e.g. `flutter pub run fontify assets/svg/ fonts/app_icons.otf --output-class-file=lib/presentation/utils/app_icons.dart -r -c AppIcons`.
Right now I have the command added to `README.md`, but it would be a lot easier if a config file could be read for this. Something like in [flutter_launcher_icons](https://pub.dev/packages/flutter_launcher_icons). I would prefer a separate config file, but maybe it could also be placed inside `pubspec.yaml` or handling both options would be even better.

What do you think of this?

**Comment by westracer** [comment]
Hello @dricholm. Thank you for the feedback, I really appreciate it.

I like the idea of reading config parameters from _pubspec.yaml_ by default and allowing to specify other config file using cli option (like in _flutter_launcher_icons_). Probably, I will implement it in the next release.

**Comment by westracer** [comment]
I've released 0.0.2 version that allows using config file and added an example usage in [readme](https://github.com/westracer/fontify#cli-tool-config-file). I'll be glad to hear any feedback.

**Comment by dricholm** [comment]
I just tried it out using the separate config file method, works perfect.
Thank you!
