### ISSUE TITLE
Call from an application

### ISSUE THREAD

**Issue by mapkbalaji** [westracer/fontify#10]
Hi,

It's possible to convert using CLI. I just need to know if I could use this package to convert to font using an application, i.e., call this package from inside my function. If possible, could you explain me how? Thanks

**Comment by westracer** [comment]
Hello. I'm sorry for not answering for so long. 

I hope you've noticed by yourself that the package exposes the API that can be used within your application. Additional info can be seen in the [readme](https://github.com/westracer/fontify#using-api).
